/* the compile-time options used to build the SQLite3 library
 *
 * https://github.com/azadkuh/sqlite-amalgamation
 */

#ifndef SQLITE3_CONFIG_H
#define SQLITE3_CONFIG_H

/* #undef SQLITE_HAVE_ZLIB */
/* #undef SQLITE_HAVE_C99_MATH_FUNCS */
/* #undef SQLITE_HAVE_TCL */

/* #undef SQLITE_ENABLE_DESERIALIZE */
#define SQLITE_ENABLE_DBSTAT_VTAB
/* #undef SQLITE_ENABLE_FTS3 */
#define SQLITE_ENABLE_FTS4
#define SQLITE_ENABLE_FTS5
/* #undef SQLITE_ENABLE_GEOPOLY */
/* #undef SQLITE_ENABLE_ICU */
/* #undef SQLITE_ENABLE_JSON1 */
#define SQLITE_ENABLE_MATH_FUNCTIONS
#define SQLITE_ENABLE_RBU
#define SQLITE_ENABLE_RTREE
/* #undef SQLITE_ENABLE_STAT4 */
#define SQLITE_OMIT_DECLTYPE
/* #undef SQLITE_OMIT_JSON */
/* #undef SQLITE_USE_URI */
#define SQLITE_ENABLE_API_ARMOR
/* #undef SQLITE_ENABLE_EXPENSIVE_ASSERT */
#define SQLITE_ENABLE_FTS3_PARENTHESIS
#define SQLITE_ENABLE_SQLLOG
#define SQLITE_LOG_CACHE_SPILL
#define SQLITE_ENABLE_IOTRACE
#define SQLITE_ENABLE_SELECTTRACE
#define SQLITE_ENABLE_WHERETRACE
#define SQLITE_FORCE_OS_TRACE
#define SQLITE_USE_FCNTL_TRACE
#define SQLITE_LOCK_TRACE
#define SQLITE_PERFORMANCE_TRACE
#define SQLITE_ENABLE_OVERSIZE_CELL_CHECK
#define SQLITE_DEBUG 1
#define SQLITE_ENABLE_ATOMIC_WRITE
#define SQLITE_ENABLE_BATCH_ATOMIC_WRITE
#define SQLITE_ENABLE_COLUMN_METADATA
#define SQLITE_ENABLE_COLUMN_USED_MASK
#define SQLITE_ENABLE_COSTMULT
#define SQLITE_ENABLE_CURSOR_HINTS
/* #undef SQLITE_ENABLE_HIDDEN_COLUMNS */
#define SQLITE_ENABLE_STMT_SCANSTATUS
#define SQLITE_ENABLE_PREUPDATE_HOOK
#define SQLITE_ENABLE_UNLOCK_NOTIFY
#define SQLITE_ENABLE_MEMORY_MANAGEMENT
#define SQLITE_ENABLE_NORMALIZE
/* #undef SQLITE_ENABLE_NULL_TRIM */
#define SQLITE_ENABLE_EXPLAIN_COMMENTS
#define SQLITE_EXPLAIN_ESTIMATED_ROWS
#define SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION
/* #undef SQLITE_ENABLE_QPSG */
#define SQLITE_ENABLE_SESSION
#define SQLITE_ENABLE_SNAPSHOT
#define SQLITE_ENABLE_SORTER_REFERENCES
#define SQLITE_DEFAULT_AUTOMATIC_INDEX 0
#define SQLITE_DEFAULT_AUTOVACUUM 0
#define SQLITE_UNLINK_AFTER_CLOSE

#define SQLITE_RECOMMENDED_OPTIONS
#if defined(SQLITE_RECOMMENDED_OPTIONS)
#   define SQLITE_DQS 0
#   define SQLITE_DEFAULT_MEMSTATUS 1
#   define SQLITE_DEFAULT_WAL_SYNCHRONOUS 1
#   define SQLITE_LIKE_DOESNT_MATCH_BLOBS
#   define SQLITE_MAX_EXPR_DEPTH 50
#   define SQLITE_OMIT_DECLTYPE
#   define SQLITE_OMIT_DEPRECATED
//#   define SQLITE_OMIT_PROGRESS_CALLBACK
#   define SQLITE_OMIT_SHARED_CACHE
#   define SQLITE_USE_ALLOCA
#endif /* SQLITE_RECOMMENDED_OPTIONS */

//#define HAVE_ISNAN
//#define SQLITE_32BIT_ROWID
//#define SQLITE_4_BYTE_ALIGNED_MALLOC

// The datatype used to store estimates of the number of rows in a table or index.
/* #undef SQLITE_64BIT_STATS */

#define SQLITE_ALLOW_COVERING_INDEX_SCAN 1
/* #undef SQLITE_ALLOW_URI_AUTHORITY */

//#define SQLITE_ATOMIC_INTRINSICS
//#define SQLITE_BITMASK_TYPE

//#define SQLITE_BUG_COMPATIBLE_20160819

/* #undef SQLITE_CASE_SENSITIVE_LIKE */
/* #undef SQLITE_CHECK_PAGES */
/* #undef SQLITE_COVERAGE_TEST */
/* #undef SQLITE_DEFAULT_AUTOMATIC_INDEX */
/* #undef SQLITE_DEFAULT_AUTOVACUUM */
//#define SQLITE_DEFAULT_CACHE_SIZE  -2000
/* #undef SQLITE_DEFAULT_CKPTFULLFSYNC */
//#define SQLITE_DEFAULT_FILE_FORMAT 4
//#define SQLITE_DEFAULT_FILE_PERMISSIONS 0644

// Enforce foreign key constraints:
/* #undef SQLITE_DEFAULT_FOREIGN_KEYS */

//#define SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT -1

// locking modes for attached databases: PAGER_LOCKINGMODE_NORMAL(0), PAGER_LOCKINGMODE_EXCLUSIVE(1)
#define SQLITE_DEFAULT_LOCKING_MODE 0

//#define SQLITE_DEFAULT_LOOKASIDE  1200,40
#ifndef SQLITE_DEFAULT_MEMSTATUS
#define SQLITE_DEFAULT_MEMSTATUS 1
#endif
//#define SQLITE_DEFAULT_MMAP_SIZE 0
//#define SQLITE_DEFAULT_PAGE_SIZE 4096
//#define SQLITE_DEFAULT_PCACHE_INITSZ 20
//#define SQLITE_DEFAULT_PROXYDIR_PERMISSIONS 0755
//#define SQLITE_DEFAULT_RECURSIVE_TRIGGERS 0
//#define SQLITE_DEFAULT_ROWEST  ~~ 200
//#define SQLITE_DEFAULT_SECTOR_SIZE 4096
//#define SQLITE_DEFAULT_SYNCHRONOUS  2
//#define SQLITE_DEFAULT_WAL_AUTOCHECKPOINT 1000
//#define SQLITE_DEFAULT_WAL_SYNCHRONOUS   SQLITE_DEFAULT_SYNCHRONOUS
//#define SQLITE_DEFAULT_WORKER_THREADS 0

/* #undef SQLITE_DIRECT_OVERFLOW_READ */
/* #undef SQLITE_DISABLE_DIRSYNC */
/* #undef SQLITE_DISABLE_FTS3_UNICODE */
/* #undef SQLITE_DISABLE_FTS4_DEFERRED */
/* #undef SQLITE_DISABLE_INTRINSIC */
/* #undef SQLITE_DISABLE_LFS */
/* #undef SQLITE_DISABLE_PAGECACHE_OVERFLOW_STATS */
/* #undef SQLITE_DISABLE_SKIPAHEAD_DISTINCT */
/* #undef SQLITE_ENABLE_8_3_NAMES */
#define SQLITE_ENABLE_API_ARMOR
#define SQLITE_ENABLE_ATOMIC_WRITE
#define SQLITE_ENABLE_BATCH_ATOMIC_WRITE
/* #undef SQLITE_ENABLE_BYTECODE_VTAB */
/* #undef SQLITE_ENABLE_CEROD */
#define SQLITE_ENABLE_COLUMN_METADATA
#define SQLITE_ENABLE_COLUMN_USED_MASK
#define SQLITE_ENABLE_COSTMULT
#define SQLITE_ENABLE_CURSOR_HINTS
/* #undef SQLITE_ENABLE_DBPAGE_VTAB */
#define SQLITE_ENABLE_DBSTAT_VTAB
/* #undef SQLITE_ENABLE_EXPENSIVE_ASSERT */
#define SQLITE_ENABLE_EXPLAIN_COMMENTS
/* #undef SQLITE_ENABLE_FTS3 */
#define SQLITE_ENABLE_FTS3_PARENTHESIS
/* #undef SQLITE_ENABLE_FTS3_TOKENIZER */
#define SQLITE_ENABLE_FTS4
#define SQLITE_ENABLE_FTS5
/* #undef SQLITE_ENABLE_GEOPOLY */
/* #undef SQLITE_ENABLE_HIDDEN_COLUMNS */
/* #undef SQLITE_ENABLE_ICU */
#define SQLITE_ENABLE_IOTRACE
/* #undef SQLITE_ENABLE_LOAD_EXTENSION */
/* #undef SQLITE_ENABLE_LOCKING_STYLE */
#define SQLITE_ENABLE_MATH_FUNCTIONS
#define SQLITE_ENABLE_MEMORY_MANAGEMENT
/* #undef SQLITE_ENABLE_MEMSYS3 */
/* #undef SQLITE_ENABLE_MEMSYS5 */
/* #undef SQLITE_ENABLE_MULTIPLEX */
#define SQLITE_ENABLE_NORMALIZE
/* #undef SQLITE_ENABLE_NULL_TRIM */
/* #undef SQLITE_ENABLE_OFFSET_SQL_FUNC */
#define SQLITE_ENABLE_OVERSIZE_CELL_CHECK
#define SQLITE_ENABLE_PREUPDATE_HOOK
/* #undef SQLITE_ENABLE_QPSG */
#define SQLITE_ENABLE_RBU
#define SQLITE_ENABLE_RTREE
#define SQLITE_ENABLE_SESSION
#define SQLITE_ENABLE_SNAPSHOT
#define SQLITE_ENABLE_SORTER_REFERENCES
#define SQLITE_ENABLE_SQLLOG
/* #undef SQLITE_ENABLE_STAT4 */
/* #undef SQLITE_ENABLE_STMTVTAB */
#define SQLITE_ENABLE_STMT_SCANSTATUS
/* #undef SQLITE_ENABLE_TREETRACE */
#define SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION
#define SQLITE_ENABLE_UNLOCK_NOTIFY
/* #undef SQLITE_ENABLE_UPDATE_DELETE_LIMIT */
/* #undef SQLITE_ENABLE_URI_00_ERROR */
/* #undef SQLITE_ENABLE_VFSTRACE */
#define SQLITE_ENABLE_WHERETRACE
/* #undef SQLITE_ENABLE_ZIPVFS */
#define SQLITE_EXPLAIN_ESTIMATED_ROWS

// unused:
/* #undef SQLITE_EXTRA_IFNULLROW */

// invoke user-def function as part of library init:     int SQLITE_EXTRA_INIT(const char*);
//#define SQLITE_EXTRA_INIT

// invoke user-def function as part of library shutdown:      void SQLITE_EXTRA_SHUTDOWN(void);
//#define SQLITE_EXTRA_SHUTDOWN

//#define SQLITE_FTS3_MAX_EXPR_DEPTH 12

// invoke    int sqlite3Fts5TestRegisterMatchinfo(sqlite3*);
//#define SQLITE_FTS5_ENABLE_TEST_MI

#undef SQLITE_FTS5_NO_WITHOUT_ROWID

#define SQLITE_HAVE_ISNAN 1

/* #undef SQLITE_HOMEGROWN_RECURSIVE_MUTEX */

/* #undef SQLITE_IGNORE_AFP_LOCK_ERRORS */
/* #undef SQLITE_IGNORE_FLOCK_LOCK_ERRORS */

// This allows better measurements of where memcpy() is used when running cachegrind.  But this macro version of memcpy() is very slow so it should not be used in production.
//#undef SQLITE_INLINE_MEMCPY

//#define SQLITE_INT64_TYPE  sqlite_int64

//#define SQLITE_INTEGRITY_CHECK_ERROR_MAX 100

//#undef SQLITE_LIKE_DOESNT_MATCH_BLOBS



#if 0                                        // TODO

#define SQLITE_LOCK_TRACE
#define SQLITE_LOG_CACHE_SPILL
/* #undef SQLITE_MALLOC_SOFT_LIMIT */
/* #undef SQLITE_MAX_ATTACHED */
/* #undef SQLITE_MAX_COLUMN */
/* #undef SQLITE_MAX_COMPOUND_SELECT */
/* #undef SQLITE_MAX_DEFAULT_PAGE_SIZE */
/* #undef SQLITE_MAX_EXPR_DEPTH */
/* #undef SQLITE_MAX_FUNCTION_ARG */
/* #undef SQLITE_MAX_LENGTH */
/* #undef SQLITE_MAX_LIKE_PATTERN_LENGTH */
/* #undef SQLITE_MAX_MEMORY */
/* #undef SQLITE_MAX_MMAP_SIZE */
/* #undef SQLITE_MAX_MMAP_SIZE_ */
/* #undef SQLITE_MAX_PAGE_COUNT */
/* #undef SQLITE_MAX_PAGE_SIZE */
/* #undef SQLITE_MAX_SCHEMA_RETRY */
/* #undef SQLITE_MAX_SQL_LENGTH */
/* #undef SQLITE_MAX_TRIGGER_DEPTH */
/* #undef SQLITE_MAX_VARIABLE_NUMBER */
/* #undef SQLITE_MAX_VDBE_OP */
/* #undef SQLITE_MAX_WORKER_THREADS */
/* #undef SQLITE_MEMDEBUG */
/* #undef SQLITE_MIXED_ENDIAN_64BIT_FLOAT */
/* #undef SQLITE_MMAP_READWRITE */
/* #undef SQLITE_MUTEX_NOOP */
/* #undef SQLITE_MUTEX_OMIT */
/* #undef SQLITE_MUTEX_PTHREADS */
/* #undef SQLITE_MUTEX_W32 */
/* #undef SQLITE_NEED_ERR_NAME */
/* #undef SQLITE_NO_SYNC */
/* #undef SQLITE_OMIT_ALTERTABLE */
/* #undef SQLITE_OMIT_ANALYZE */
/* #undef SQLITE_OMIT_ATTACH */
/* #undef SQLITE_OMIT_AUTHORIZATION */
/* #undef SQLITE_OMIT_AUTOINCREMENT */
/* #undef SQLITE_OMIT_AUTOINIT */
/* #undef SQLITE_OMIT_AUTOMATIC_INDEX */
/* #undef SQLITE_OMIT_AUTORESET */
/* #undef SQLITE_OMIT_AUTOVACUUM */
/* #undef SQLITE_OMIT_BETWEEN_OPTIMIZATION */
/* #undef SQLITE_OMIT_BLOB_LITERAL */
/* #undef SQLITE_OMIT_CAST */
/* #undef SQLITE_OMIT_CHECK */
/* #undef SQLITE_OMIT_COMPLETE */
/* #undef SQLITE_OMIT_COMPOUND_SELECT */
/* #undef SQLITE_OMIT_CONFLICT_CLAUSE */
/* #undef SQLITE_OMIT_CTE */
/* #undef SQLITE_OMIT_DATETIME_FUNCS */
#define SQLITE_OMIT_DECLTYPE
/* #undef SQLITE_OMIT_DEPRECATED */
/* #undef SQLITE_OMIT_DESERIALIZE */
/* #undef SQLITE_OMIT_DISKIO */
/* #undef SQLITE_OMIT_EXPLAIN */
/* #undef SQLITE_OMIT_FLAG_PRAGMAS */
/* #undef SQLITE_OMIT_FLOATING_POINT */
/* #undef SQLITE_OMIT_FOREIGN_KEY */
/* #undef SQLITE_OMIT_GET_TABLE */
/* #undef SQLITE_OMIT_HEX_INTEGER */
/* #undef SQLITE_OMIT_INCRBLOB */
/* #undef SQLITE_OMIT_INTEGRITY_CHECK */
/* #undef SQLITE_OMIT_INTROSPECTION_PRAGMAS */
/* #undef SQLITE_OMIT_JSON */
/* #undef SQLITE_OMIT_LIKE_OPTIMIZATION */
/* #undef SQLITE_OMIT_LOAD_EXTENSION */
/* #undef SQLITE_OMIT_LOCALTIME */
/* #undef SQLITE_OMIT_LOOKASIDE */
/* #undef SQLITE_OMIT_MEMORYDB */
/* #undef SQLITE_OMIT_OR_OPTIMIZATION */
/* #undef SQLITE_OMIT_PAGER_PRAGMAS */
/* #undef SQLITE_OMIT_PARSER_TRACE */
/* #undef SQLITE_OMIT_POPEN */
/* #undef SQLITE_OMIT_PRAGMA */
/* #undef SQLITE_OMIT_PROGRESS_CALLBACK */
/* #undef SQLITE_OMIT_QUICKBALANCE */
/* #undef SQLITE_OMIT_REINDEX */
/* #undef SQLITE_OMIT_SCHEMA_PRAGMAS */
/* #undef SQLITE_OMIT_SCHEMA_VERSION_PRAGMAS */
/* #undef SQLITE_OMIT_SHARED_CACHE */
/* #undef SQLITE_OMIT_SHUTDOWN_DIRECTORIES */
/* #undef SQLITE_OMIT_SUBQUERY */
/* #undef SQLITE_OMIT_TCL_VARIABLE */
/* #undef SQLITE_OMIT_TEMPDB */
/* #undef SQLITE_OMIT_TEST_CONTROL */
/* #undef SQLITE_OMIT_TRACE */
/* #undef SQLITE_OMIT_TRIGGER */
/* #undef SQLITE_OMIT_TRUNCATE_OPTIMIZATION */
/* #undef SQLITE_OMIT_UTF16 */
/* #undef SQLITE_OMIT_VACUUM */
/* #undef SQLITE_OMIT_VIEW */
/* #undef SQLITE_OMIT_VIRTUALTABLE */
/* #undef SQLITE_OMIT_WAL */
/* #undef SQLITE_OMIT_WSD */
/* #undef SQLITE_OMIT_XFER_OPT */
#define SQLITE_PERFORMANCE_TRACE
/* #undef SQLITE_POWERSAFE_OVERWRITE */
/* #undef SQLITE_PREFER_PROXY_LOCKING */
/* #undef SQLITE_PROXY_DEBUG */
/* #undef SQLITE_REVERSE_UNORDERED_SELECTS */
/* #undef SQLITE_RTREE_INT_ONLY */
/* #undef SQLITE_SECURE_DELETE */
/* #undef SQLITE_SMALL_STACK */
/* #undef SQLITE_SORTER_PMASZ */
/* #undef SQLITE_SOUNDEX */
//#define SQLITE_STAT4_SAMPLES 24
/* #undef SQLITE_STMTJRNL_SPILL */
/* #undef SQLITE_SUBSTR_COMPATIBILITY */
/* #undef SQLITE_SYSTEM_MALLOC */
/* #undef SQLITE_TCL */
/* #undef SQLITE_TEMP_STORE */
/* #undef SQLITE_TEST */
/* #undef SQLITE_THREADSAFE */
#define SQLITE_UNLINK_AFTER_CLOSE
/* #undef SQLITE_UNTESTABLE */
/* #undef SQLITE_USER_AUTHENTICATION */
/* #undef SQLITE_USE_ALLOCA */
#define SQLITE_USE_FCNTL_TRACE
/* #undef SQLITE_USE_URI */
/* #undef SQLITE_VDBE_COVERAGE */
/* #undef SQLITE_WIN32_MALLOC */
/* #undef SQLITE_ZERO_MALLOC */

#endif


#if defined(SQLITE_OMIT_DECLTYPE) && defined(SQLITE_ENABLE_COLUMN_METADATA)
#  undef SQLITE_OMIT_DECLTYPE
#endif

#ifdef SQLITE_ENABLE_SQLLOG
void sqlite3_init_sqllog(void);
#endif

#endif /* SQLITE3_CONFIG_H */
